# Generated by Django 2.2.6 on 2019-12-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20191223_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='books', to='book.Genre'),
        ),
    ]
