# Generated by Django 2.2.6 on 2019-12-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20191223_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='genre',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
