# Generated by Django 2.2.6 on 2019-12-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20191223_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name_en',
            new_name='nameEn',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name_ru',
            new_name='nameRu',
        ),
    ]
