# Generated by Django 2.2.6 on 2019-12-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20191223_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='nameEn',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='nameRu',
            new_name='name_ru',
        ),
    ]
